/* Forge vault — every generated file as plain text, so nothing is ever out of reach
 * even when the preview frame blocks binary downloads. */
import JSZip from "jszip";
import type { GenOpts } from "./projects";
import { appIcon, workingAppHtml } from "./projects";
import { buildHta } from "./hta";
import { workflowYaml } from "./cloudbuild";
import { slugify } from "./engine";
import { saveBlob } from "./save";

export interface VaultFile {
  path: string;
  note: string;
  content: string;
}

const electronMain = (appName: string) => `const { app, BrowserWindow } = require("electron");
const path = require("path");
function createWindow() {
  const win = new BrowserWindow({
    width: 1280, height: 800, backgroundColor: "#0b0d12",
    title: ${JSON.stringify(appName)},
    webPreferences: { contextIsolation: true },
  });
  win.loadFile(path.join(__dirname, "index.html"));
}
app.whenReady().then(createWindow);
app.on("window-all-closed", () => app.quit());
`;

function guide(o: GenOpts): string {
  const slug = slugify(o.appName);
  return `# ${o.appName} — forge vault
Cloned from: ${o.profile.url}
Generated by CloneForge · v${o.version}

## Run it RIGHT NOW (no build)
1. Windows PC  → save "${slug}.hta" anywhere, double-click it. Done.
2. Phone / any OS → save "app/index.html", open it in Chrome,
   menu ▸ "Add to Home Screen" (or "Install"). It is the full app.

## Compile the genuine installers on GitHub's free runners
1. Create a repo (any name), then add:
     app/...  +  .github/workflows/cloneforge.yml  (both in this vault)
   Quickest: gh auth login && gh repo create ${slug}-forged --public --source=. --push
2. The workflow auto-compiles on push (Gradle + electron-builder):
     → ${o.appName}-android.apk   (real, installable)
     → ${o.appName}-Setup.exe     (real NSIS installer)
3. Repo ▸ Actions ▸ run ▸ artifact "installers" ▸ download.

## Or the zero-cloud route
- APK: wrap app/ with Capacitor → npx cap add android && ./gradlew assembleDebug
- EXE: drop main.js + package.json next to app/index.html → npm i && npx electron-builder --win nsis
`;
}

export function vaultFiles(o: GenOpts): VaultFile[] {
  const slug = slugify(o.appName);
  return [
    {
      path: `${slug}.hta`,
      note: "windows app · double-click to run",
      content: buildHta({ appName: o.appName, profile: o.profile, accent: o.accent }),
    },
    {
      path: "app/index.html",
      note: "the app itself · phone + pc · installable",
      content: workingAppHtml(o),
    },
    { path: "app/icon.svg", note: "app icon", content: appIcon(o) },
    { path: "desktop/main.js", note: "electron shell → real .exe", content: electronMain(o.appName) },
    {
      path: ".github/workflows/cloneforge.yml",
      note: "cloud compiler recipe · apk + exe",
      content: workflowYaml(o.appName),
    },
    { path: "BUILD-GUIDE.md", note: "every path to a working app", content: guide(o) },
  ];
}

export async function downloadVaultZip(o: GenOpts): Promise<void> {
  const zip = new JSZip();
  for (const f of vaultFiles(o)) zip.file(f.path, f.content);
  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  saveBlob(`${slugify(o.appName)}-forge-vault.zip`, blob);
}
